(function(){
  const lessonCode=window.SCIENCE_LESSON.id.toUpperCase();
  const config={classes:["KIDS 7", "KIDS 8", "KIDS 10", "KIDS 11", "KIDS 14", "KIDS 15", "KIDS 17", "KIDS 18", "KIDS 19", "KIDS 20", "KIDS 21", "KIDS 22", "KIDS 23", "KIDS 25", "KIDS 26", "KIDS 27", "KIDS 28", "KIDS 29", "KIDS 30", "KIDS 31", "KIDS 32", "KIDS 33", "KIDS 34", "KIDS 35", "KIDS 36", "KIDS 37", "KIDS 38", "KIDS 39", "KIDS 40"],videoForm:'https://docs.google.com/forms/d/e/1FAIpQLSf6T_4KVBN6LI9oFJl5cgnZPk0woNXjxmtlHFM7gWY6OJTHgg/viewform',videoEntries:{name:'entry.1366919347',className:'entry.961891111',code:'entry.989301220'},scoreForm:'https://docs.google.com/forms/d/e/1FAIpQLSf70nZdOXNSz7PGtMGckvVV6S4IJAT7sid9BBvhFEAbuEYd-A/viewform',scoreEntries:{name:'entry.626306593',className:'entry.567316915',code:'entry.1998956975',score:'entry.144780084',total:'entry.1804999547',percent:'entry.1191306277',attempt:'entry.552906711'}};
  const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const profileKey='science-g3-student-profile-v1';
  function getProfile(){try{const p=JSON.parse(localStorage.getItem(profileKey)||'null');return p&&typeof p.name==='string'&&p.name.trim().length>=2&&config.classes.includes(p.className)?p:null;}catch{return null;}}
  function key(p){return (window.SCIENCE_LESSON.id==='science-g3-01'?'science-g3-germs-v1:':window.SCIENCE_LESSON.id+'-v1:')+(p?encodeURIComponent(p.className+'|'+p.name.toLowerCase().trim().replace(/\s+/g,' ')):'preview');}
  function gate(main){
    main.innerHTML=`<p class="eyebrow">SCIENCE G3 · BÀI ${String(window.SCIENCE_LESSON.number).padStart(2,'0')}</p><h1>${escape(window.SCIENCE_LESSON.title)}</h1><p class="intro">Nghe và điền 30 từ, cụm từ → học mindmap → quay thuyết trình và trả lời câu hỏi → nộp cả hai video một lần. Mỗi chặng có thể làm vào một ngày khác nhau.</p><section class="profile-panel"><h2>Thông tin học sinh</h2><p>Ghi đúng tên tiếng Anh và chọn lớp để lưu tiến độ riêng của em.</p><form id="profile-form"><div class="profile-fields"><label>Tên tiếng Anh<input name="name" autocomplete="name" minlength="2" maxlength="60" required placeholder="Ví dụ: Anna"></label><label>Lớp<select name="className" required><option value="" selected disabled>Chọn lớp KIDS của em</option>${config.classes.map(c=>`<option>${c}</option>`).join('')}</select></label></div><button class="primary">Bắt đầu / Tiếp tục bài</button></form><p class="profile-help">Bài đang làm dở được lưu trên cùng thiết bị và trình duyệt. Bấm “Đã xong – Nộp bài” để tự ghi điểm nghe. Video có thể quay và nộp vào ngày khác.</p></section>`;
    main.querySelector('form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);const p={name:String(data.get('name')).trim().replace(/\s+/g,' '),className:String(data.get('className'))};if(p.name.length<2||!config.classes.includes(p.className))return;try{localStorage.setItem(profileKey,JSON.stringify(p));location.reload();}catch{main.querySelector('.profile-help').textContent='Trình duyệt đang chặn lưu tiến độ. Em bật lưu trữ để tiếp tục bài qua nhiều lần học.';}};
  }
  function badge(p){const header=document.querySelector('header');let box=header.querySelector('.profile-badge');if(box)box.remove();box=document.createElement('div');box.className='profile-badge';box.innerHTML=`<span><b>${escape(p.name)}</b> · ${escape(p.className)}</span>`;header.querySelector('.edition').hidden=true;header.append(box);}
  function videoURL(p){const url=new URL(config.videoForm);url.searchParams.set('usp','pp_url');url.searchParams.set(config.videoEntries.name,p.name);url.searchParams.set(config.videoEntries.className,p.className);url.searchParams.set(config.videoEntries.code,lessonCode);return url.href;}
  function videoPanel(p){const box=document.createElement('section');box.className='submission-panel';box.innerHTML=`<h2>Nộp cả hai video trong một lần</h2><p><strong>Video 1:</strong> Thuyết trình theo mindmap.<br><strong>Video 2:</strong> Trình bày câu trả lời cho ${window.SCIENCE_LESSON.questions.length} câu hỏi đọc hiểu.</p><p>Chuẩn bị đủ hai video, mở Form, tải vào hai ô tương ứng hoặc dán hai liên kết (mỗi liên kết một dòng), rồi bấm <strong>Gửi một lần</strong>.</p><a class="primary" href="${escape(videoURL(p))}" target="_blank" rel="noopener">Mở Form nộp cả hai video ↗</a><small>Tên, lớp và mã bài ${escape(lessonCode)} đã điền sẵn trong Form Science G1/G2. Xem trước hoặc lưu nháp không tính là đã nộp. Chỉ bài đã gửi qua Form mới được hệ thống ghi nhận; điểm nghe được lưu riêng.</small>`;return box;}
  function scoreURL(p,attempt){const url=new URL(config.scoreForm);url.searchParams.set('usp','pp_url');const values={name:p.name,className:p.className,code:lessonCode+'-LS',score:attempt.score,total:attempt.total,percent:attempt.percent,attempt:attempt.id};for(const [k,v] of Object.entries(values))url.searchParams.set(config.scoreEntries[k],v);return url.href;}
  const scoreEndpoint='https://script.google.com/macros/s/AKfycbwF7eG13BCVxqtuKGFif_Z7WeuexOd57IMSdW575r3rNk-ykxaXn_qdssGapnKLEYhWyA/exec';
  async function submitScore(p,attempt){
    const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),45000);
    try {
      const response=await fetch(scoreEndpoint,{method:'POST',body:new URLSearchParams({action:'science-submit',payload:JSON.stringify({lessonCode:lessonCode,name:p.name,className:p.className,attemptId:attempt.id,answers:attempt.answers})}),signal:controller.signal,redirect:'follow'});
      if(!response.ok)throw Error('NETWORK');
      const result=await response.json(),r=result.receipt;
      if(!result.ok||!r||r.id!==attempt.id||r.code!==lessonCode+'-LS'||r.total!==attempt.total||r.score!==attempt.score)throw Error(result.error||'UNCONFIRMED');
      return r;
    }finally{clearTimeout(timeout);}
  }
  function scorePanel(p,attempt,receipt,status){const box=document.createElement('section');box.className='submission-panel';
    box.innerHTML=receipt?`<strong>✓ Đã ghi điểm nghe</strong><p><b>${receipt.score}/${receipt.total}</b> · <b>${receipt.score10.toLocaleString('vi-VN')}/10</b>. Điểm lần đầu đã được lưu cho cô.</p><small>Mindmap đã mở. Em có thể nghỉ và quay lại ngày mai trên cùng thiết bị, trình duyệt để học tiếp. Quay và nộp video ở chặng sau.</small>`:status==='sending'?'<strong>Đang ghi điểm…</strong><p>Em chờ xác nhận; chưa cần bấm lại.</p>':'<strong>Chưa xác nhận ghi được điểm</strong><p>Bài làm đã lưu trên thiết bị. Kiểm tra kết nối rồi bấm gửi lại; hệ thống dùng cùng mã lượt để tránh ghi trùng.</p><button class="primary" id="retry-score">Gửi lại điểm</button>';
    return box;
  }
  window.ScienceSystem={config,getProfile,key,gate,badge,videoURL,videoPanel,scoreURL,scorePanel,submitScore};
})();
